---
language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: pip install argparse importlib behave
# command to test
script: behave

notifications:
  email:
    recipients:
      - darkfoxprime@gmail.com
